### ISSUE TITLE
Published Container Image and helm support

### ISSUE THREAD

**Issue by pkwiatkowski1** [testifysec/archivista#50]
I've worked on deploying Archivista to a Kubernetes cluster with a simple generated helm chart and a locally built image.

It'd be good to get a published image into a public facing Container Registry to make it easier to deploy downstream.

Also, I'd like to contribute back the helm chart we're using for deployments if that's desired.

**Comment by colek42** [comment]
We will be publishing images soon.  @mikhailswift where should be put Helm charts?

**Comment by colek42** [comment]
We are thinking making a new repo for charts is the way to go.

**Comment by lmco-dvinci** [comment]
Hello, I work with Pat - anything new on this, before I begin work on building the image internally?

**Comment by colek42** [comment]
@lmco-dvinci 

We actually just started publishing images:

https://github.com/testifysec/archivista/pkgs/container/archivista

I'll get a tagged release out on Monday.

Also, we have a repo for charts:  https://github.com/testifysec/charts

If you have something we will certainly accept a PR, otherwise it might be a bit before we create a helm chart since we use kustomize internally.

**Comment by lmco-dvinci** [comment]
Sweet, thanks. Feel free to close this.

**Comment by jkjell** [comment]
We have a chart now in https://github.com/testifysec/charts
